ArcBundle\Entity\Content:
    type: entity
    table: null
    repositoryClass: ArcBundle\Repository\ContentRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        title:
            type: string
            length: 255
        description:
            type: string
            length: 255
            nullable: true
        picture:
            type: string
            length: 255
        pictureAlt:
            type: string
            length: 255

    ManyToOne:
        coach:
            targetEntity: Coach
            inversedBy: contents
            joinColumn:
                name: coach_id
                referencedColumnName: id
    lifecycleCallbacks: {  }
